import * as admin from 'firebase-admin';


admin.initializeApp({
    credential: admin.credential.applicationDefault(),
    databaseURL: 'https://<DATABASE_NAME>.firebaseio.com'
});

var refreshToken; // Get refresh token from OAuth2 flow
admin.initializeApp({
    credential: admin.credential.refreshToken(refreshToken),
    databaseURL: 'https://<DATABASE_NAME>.firebaseio.com'
});

// Initialize the default app
var admin = require('firebase-admin');
var app = admin.initializeApp();


//Fetching a users data using their uid (unique ID generated by FireBase. Returns as a 'UserRecord' object)
admin.auth().getUser(uid)
  .then(function(userRecord) {
    // See the UserRecord reference doc for the contents of userRecord.
    console.log('Successfully fetched user data:', userRecord.toJSON());
  })
  .catch(function(error) {
    console.log('Error fetching user data:', error);
  });

//Fetching a user using their email 
admin.auth().getUserByEmail(email)
    .then(function(userRecord) {
     // See the UserRecord reference doc for the contents of userRecord.
     console.log('Successfully fetched user data:', userRecord.toJSON());
    })
    .catch(function(error) {
        console.log('Error fetching user data:', error);
    });

//Fetching a user by their phone number
admin.auth().getUserByPhoneNumber(phoneNumber)
  .then(function(userRecord) {
    // See the UserRecord reference doc for the contents of userRecord.
    console.log('Successfully fetched user data:', userRecord.toJSON());
  })
  .catch(function(error) {
    console.log('Error fetching user data:', error);
  });


//Creating a new user
admin.auth().createUser({
    email: 'user@example.com',
    emailVerified: false,
    phoneNumber: '+11234567890',
    password: 'secretPassword',
    displayName: 'John Doe',
    photoURL: 'http://www.example.com/12345678/photo.png',
    disabled: false
  })
    .then(function(userRecord) {
      // See the UserRecord reference doc for the contents of userRecord.
      console.log('Successfully created new user:', userRecord.uid);
    })
    .catch(function(error) {
      console.log('Error creating new user:', error);
    });
